### ISSUE TITLE
Console logs do not output anything beyond "navigated to file" on initial index.html file load

### ISSUE THREAD

**Issue by ShqipognjaLL** [riccardobl/JavaFXWebEngineDebugger#1]

**Comment by riccardobl** [comment]
The protocol changed in chrome, it should still work with any client that support webkit remote debug protocol (safari?).

The protocols are similar, so it should be easy to write a translation layer, i'll look into it. 

### References
Chrome debug protocol: https://chromedevtools.github.io/debugger-protocol-viewer/tot/

Webkit debug protocol: https://github.com/WebKit/webkit/tree/master/Source/JavaScriptCore/inspector/protocol

**Comment by riccardobl** [comment]
Should now be fixed in fdd10ea43ae1818bb0095d000964e5154adce998

Usage info: https://github.com/riccardobl/JavaFXWebEngineDebugger/blob/master/README.md#chrome-translation-layer
